simple_it_claire_component_part_metadata_show_rating:
    pattern: /rating
    defaults: { _controller: SimpleITClaireAppBundle:Course/Component/MetadataByPart:showRating }
    requirements:
            _method: GET

simple_it_claire_component_part_metadata_edit_description:
    pattern: /description/edit
    defaults: { _controller: SimpleITClaireAppBundle:Course/Component/MetadataByPart:editDescription }
    requirements:
            _method: GET|POST

simple_it_claire_component_part_metadata_edit_image:
    pattern: /image/edit
    defaults: { _controller: SimpleITClaireAppBundle:Course/Component/MetadataByPart:editImage }
    requirements:
            _method: GET|POST

simple_it_claire_component_part_metadata_edit_difficulty:
    pattern: /difficulty/edit
    defaults: { _controller: SimpleITClaireAppBundle:Course/Component/MetadataByPart:editDifficulty }
    requirements:
            _method: GET|POST

simple_it_claire_component_part_metadata_edit_duration:
    pattern: /duration/edit
    defaults: { _controller: SimpleITClaireAppBundle:Course/Component/MetadataByPart:editDuration }
    requirements:
            _method: GET|POST
