simple_it_claire_component_part_edit:
    pattern: /{courseId}/parts/{partId}
    defaults: { _controller: SimpleITClaireAppBundle:Course/Component/Part:edit }
    requirements:
            _method: GET|POST

simple_it_claire_component_part_metadata:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/course/component_part_metadata.yml"
    prefix:   /{courseIdentifier}/parts/{partIdentifier}/metadatas/

