simple_it_claire_course_component_course_list:
    pattern: /
    defaults: { _controller: SimpleITClaireAppBundle:Course/Component/Course:list }
    requirements:
        _method: GET

simple_it_claire_course_component_course_search_list:
    pattern: /search
    defaults: { _controller: SimpleITClaireAppBundle:Course/Component/Course:searchList, paginationUrl: null }
    requirements:
        _method: GET

simple_it_claire_course_component_course_content_edit:
    pattern: /{courseId}/content
    defaults: { _controller: SimpleITClaireAppBundle:Course/Component/CourseContent:edit }
    requirements:
        _method: POST

simple_it_claire_course_component_course_introduction_edit:
    pattern: /{courseId}/introduction
    defaults: { _controller: SimpleITClaireAppBundle:Course/Component/Course:editIntroduction }
    requirements:
        _method: POST

simple_it_claire_component_course_toc_edit:
    pattern: /{courseId}/toc
    defaults: { _controller: SimpleITClaireAppBundle:Course/Component/TocByCourse:edit }
    requirements:
        _method: POST

simple_it_claire_course_component_course_display_level_edit:
    pattern: /{courseId}/displayLevel
    defaults: { _controller: SimpleITClaireAppBundle:Course/Component/Course/DisplayLevel:edit }
    requirements:
        _method: POST

simple_it_claire_component_course_status_published:
    pattern: /{courseId}/publish
    defaults: { _controller : SimpleITClaireAppBundle:Course/Component/Workflow/Workflow:changeCourseToPublished }
    requirements :
        -method: POST

simple_it_claire_component_course_status_waiting_for_publication:
    pattern: /{courseId}/submitToPublication
    defaults: { _controller : SimpleITClaireAppBundle:Course/Component/Workflow/Workflow:changeCourseToWaitingForPublication }
    requirements :
        -method: POST

simple_it_claire_course_component_course_difficulty_edit:
    pattern: /{courseId}/difficulty
    defaults: { _controller: SimpleITClaireAppBundle:Course/Component/Course/CourseDifficulty:edit }
    requirements:
        _method: POST

simple_it_claire_course_component_course_description_edit:
    pattern: /{courseId}/description
    defaults: { _controller: SimpleITClaireAppBundle:Course/Component/Course/CourseDescription:edit }
    requirements:
        _method: POST

simple_it_claire_course_component_course_title_edit:
    pattern: /{courseId}/edit
    defaults: { _controller: SimpleITClaireAppBundle:Course/Component/Course/CourseTitle:edit }
    requirements:
            _method: POST
