simple_it_claire_course_course_create:
    pattern: /create
    defaults: { _controller: SimpleITClaireAppBundle:Course/Component/Course:create }
    requirements:
        _method: GET

simple_it_claire_course_waiting_for_publication_list:
    pattern: /waiting-for-publication-list
    defaults : { _controller: SimpleITClaireAppBundle:Course/Course:waitingForPublicationList }
    requirements:
            _method: GET

simple_it_claire_part:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/course/part.yml"
    prefix:   /{courseIdentifier}/parts

simple_it_claire_course_metadata:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/course/component_course_metadata.yml"
    prefix:   /{courseId}/metadatas

simple_it_claire_component_course_part_content_edit:
    pattern: /{courseId}/parts/{partId}/content
    defaults: { _controller: SimpleITClaireAppBundle:Course/Component/PartContent:edit }
    requirements:
        _method: POST
