SimpleIT_Claire_course_view:
    pattern:  /{course}
    defaults: { _controller: SimpleITClaireAppBundle:Course:show }
    requirements:
        _method: get

SimpleIT_Claire_course_list:
    pattern:  /
    defaults: { _controller: SimpleITClaireAppBundle:Course:list }
    requirements:
        _method: get

SimpleIT_Claire_course_create:
    pattern:  /create
    defaults: { _controller: SimpleITClaireAppBundle:Course:create }
    requirements:
        _method: get|post

SimpleIT_Claire_course_edit:
    pattern:  /edit/{slug}
    defaults: { _controller: SimpleITClaireAppBundle:Course:edit }
    requirements:
        _method: get|post
