web_exercise_model_create_view:
    pattern: /create
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/ExerciseModel:createExerciseModelView }
    requirements:
        _method: GET

web_exercise_model_create:
    pattern: /create
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/ExerciseModel:create }
    requirements:
        _method: POST

web_exercise_model_title_edit_view:
    pattern: /{exerciseModelId}/title
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/ExerciseModel:editTitleView }
    requirements:
        _method: GET

web_exercise_model_title_edit:
    pattern: /{exerciseModelId}/title
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/ExerciseModel:titleEdit }
    requirements:
        _method: POST

web_exercise_model_draft_edit_view:
    pattern: /{exerciseModelId}/draft
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/ExerciseModel:editDraftView }
    requirements:
        _method: GET

web_exercise_model_draft_edit:
    pattern: /{exerciseModelId}/draft
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/ExerciseModel:draftEdit }
    requirements:
        _method: POST

web_exercise_model_content_edit_view:
    pattern: /{exerciseModelId}/content
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/ExerciseModel:contentEdit }
    requirements:
        _method: GET

web_exercise_model_content_edit:
    pattern: /{exerciseModelId}/content
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/ExerciseModel:contentEdit }
    requirements:
        _method: POST

web_exercise_model_required_resource_edit_view:
    pattern: /{exerciseModelId}/required-resources
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/RequiredResourceByExerciseModel:editRequiredResourcesView }
    requirements:
        _method: GET

web_exercise_model_required_resource_edit:
    pattern: /{exerciseModelId}/required-resources
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/RequiredResourceByExerciseModel:RequiredResourceEdit }
    requirements:
        _method: POST

web_exercise_model_list:
    pattern: /
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/ExerciseModel:list }
    requirements:
        _method: GET

web_exercise_model_view:
    pattern: /{exerciseModelId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/ExerciseModel:view }
    requirements:
        _method: GET
        exerciseModelId: \d+

web_exercise_model_edit:
    pattern: /{exerciseModelId}/edit
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/ExerciseModel:editView }
    requirements:
        _method: GET
        exerciseModelId: \d+

web_exercise_model_delete:
    pattern: /{exerciseModelId}/delete
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/ExerciseModel:delete }
    requirements:
        _method: GET
        exerciseModelId: \d+

web_exercise_model_add_to_perso:
    pattern: /{exerciseModelId}/add-to-perso
    defaults: { _controller:SimpleITClaireExerciseBundle:Exercise/Component/OwnerExerciseModelByExerciseModel:addToPerso }
    requirements:
        _method: GET
        exerciseModelId: \d+

web_exercise_model_try:
    pattern: /{exerciseModelId}/try
    defaults: { _controller:SimpleITClaireExerciseBundle:Exercise/Component/ExerciseModel:try }
    requirements:
        _method: GET
        exerciseModelId: \d+

web_exercise_model_duplicate:
    pattern: /{exerciseModelId}/duplicate
    defaults: { _controller:SimpleITClaireExerciseBundle:Exercise/Component/ExerciseModel:duplicate }
    requirements:
        _method: GET
        exerciseModelId: \d+


