web_resource_edit:
    pattern: /{resourceId}/edit
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/Resource:editView }
    requirements:
        _method: GET
        resourceId: \d+

web_resource_create_view:
    pattern: /create
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/Resource:createResourceView }
    requirements:
        _method: GET

web_resource_create:
    pattern: /create
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/Resource:create }
    requirements:
        _method: POST

web_resource_delete:
    pattern: /{resourceId}/delete
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/Resource:delete }
    requirements:
        _method: GET
        resourceId: \d+

web_resource_type_edit_view:
    pattern: /{resourceId}/type
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/Resource:editTypeView }
    requirements:
        _method: GET
        resourceId: \d+

web_resource_type_edit:
    pattern: /{resourceId}/type
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/Resource:typeEdit }
    requirements:
        _method: POST
        resourceId: \d+

web_resource_content_edit_view:
    pattern: /{resourceId}/content
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/Resource:editContentView }
    requirements:
        _method: GET
        resourceId: \d+

web_resource_picture_content_edit:
    pattern: /{resourceId}/picture/content
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/Resource:pictureContentEdit }
    requirements:
        _method: POST
        resourceId: \d+

web_resource_text_content_edit:
    pattern: /{resourceId}/text/content
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/Resource:textContentEdit }
    requirements:
        _method: POST
        resourceId: \d+

web_resource_mcquestion_content_edit:
    pattern: /{resourceId}/mcquestion/content
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/Resource:mcQuestionContentEdit }
    requirements:
        _method: POST
        resourceId: \d+

web_resource_required_resource_edit_view:
    pattern: /{resourceId}/required-resources
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/RequiredResourceByResource:editRequiredResourcesView }
    requirements:
        _method: GET
        resourceId: \d+

web_resource_required_resource_edit:
    pattern: /{resourceId}/required-resources
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/RequiredResourceByResource:RequiredResourceEdit }
    requirements:
        _method: POST
        resourceId: \d+

web_resource_add_to_perso:
    pattern: /{resourceId}/add-to-perso
    defaults: { _controller: SimpleITClaireExerciseBundle:Exercise/Component/OwnerResourceByResource:addToPerso }
    requirements:
        _method: GET
        resourceId: \d+

web_resource_duplicate:
    pattern: /{resourceId}/duplicate
    defaults: { _controller:SimpleITClaireExerciseBundle:Exercise/Component/Resource:duplicate }
    requirements:
        _method: GET
        resourceId: \d+
