api_knowledge_list:
    pattern:  /
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/Knowledge:list }
    methods: [GET]
    requirements:
        _format: json

api_knowledge_create:
    pattern:  /
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/Knowledge:create }
    methods: [POST]
    requirements:
        _format: json

api_knowledge_view:
    pattern:  /{knowledgeId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/Knowledge:view }
    methods: [GET]
    requirements:
        _format: json
        knowledgeId: \d+

api_knowledge_edit:
    pattern:  /{knowledgeId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/Knowledge:edit }
    methods: [PUT]
    requirements:
        _format: json
        knowledgeId: \d+

api_knowledge_delete:
    pattern:  /{knowledgeId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/Knowledge:delete }
    methods: [DELETE]
    requirements:
        _format: json
        knowledgeId: \d+

api_knowledge_add_requirement:
    pattern:  /{knowledgeId}/required-knowledges/{reqKnoId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/RequiredKnowledgeByKnowledge:add }
    methods: [POST]
    requirements:
        _format: json
        knowledgeId: \d+
        reqResId: \d+

api_knowledge_delete_requirement:
    pattern:  /{knowledgeId}/required-knowledges/{reqKnoId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/RequiredKnowledgeByKnowledge:delete }
    methods: [DELETE]
    requirements:
        _format: json
        knowledgeId: \d+
        reqResId: \d+

api_knowledge_update_required_knowledge:
    pattern:  /{knowledgeId}/required-knowledges/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/RequiredKnowledgeByKnowledge:edit }
    methods: [PUT]
    requirements:
        _format: json
        knowledgeId: \d+
        reqResId: \d+

api_owner_knowledge_create_by_knowledge:
    pattern:  /{knowledgeId}/owner-knowledges/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/OwnerKnowledgeByKnowledge:create }
    methods: [POST]
    requirements:
        _format: json
        knowledgeId: \d+

api_owner_knowledge_edit_by_knowledge:
    pattern:  /{knowledgeId}/owner-knowledges/{ownerKnowledgeId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/OwnerKnowledgeByKnowledge:edit }
    methods: [PUT]
    requirements:
        _format: json
        knowledgeId: \d+
        ownerKnowledgeId: \d+

api_owner_knowledge_list_by_knowledge:
    pattern:  /{knowledgeId}/owner-knowledges/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/OwnerKnowledgeByKnowledge:list }
    methods: [GET]
    requirements:
        _format: json
        knowledgeId: \d+

api_owner_knowledge_view_by_knowledge:
    pattern:  /{knowledgeId}/owner-knowledges/{ownerKnowledgeId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/OwnerKnowledgeByKnowledge:view }
    methods: [GET]
    requirements:
        _format: json
        ownerKnowledgeId: \d+
        knowledgeId: \d+
