api_owner_resource_list:
    pattern:  /
    defaults: { _controller: SimpleITClaireExerciseBundle:ExerciseResource/OwnerResource:list }
    methods: [GET]
    requirements:
        _format: json

api_owner_resource_view:
    pattern:  /{ownerResourceId}
    defaults: { _controller: SimpleITClaireExerciseBundle:ExerciseResource/OwnerResource:view }
    methods: [GET]
    requirements:
        _format: json
        ownerResourceId: \d+

api_owner_resource_edit:
    pattern:  /{ownerResourceId}
    defaults: { _controller: SimpleITClaireExerciseBundle:ExerciseResource/OwnerResource:edit }
    methods: [PUT]
    requirements:
        _format: json
        ownerResourceId: \d+


api_owner_resource_delete:
    pattern:  /{ownerResourceId}
    defaults: { _controller: SimpleITClaireExerciseBundle:ExerciseResource/OwnerResource:delete }
    methods: [DELETE]
    requirements:
        _format: json
        ownerResourceId: \d+

api_metadata_list_by_owner_resource:
    pattern:  /{ownerResourceId}/metadatas/
    defaults: { _controller: SimpleITClaireExerciseBundle:ExerciseResource/MetadataByOwnerResource:list }
    methods: [GET]
    requirements:
        _format: json
        ownerResourceId: \d+

api_metadata_edit_all_by_owner_resource:
    pattern:  /{ownerResourceId}/metadatas/
    defaults: { _controller: SimpleITClaireExerciseBundle:ExerciseResource/MetadataByOwnerResource:editAll }
    methods: [PUT]
    requirements:
        _format: json
        ownerResourceId: \d+

api_metadata_view_by_owner_resource:
    pattern:  /{ownerResourceId}/metadatas/{metadataKey}
    defaults: { _controller: SimpleITClaireExerciseBundle:ExerciseResource/MetadataByOwnerResource:view }
    methods: [GET]
    requirements:
        _format: json
        ownerResourceId: \d+

api_metadata_create_by_owner_resource:
    pattern:  /{ownerResourceId}/metadatas/
    defaults: { _controller: SimpleITClaireExerciseBundle:ExerciseResource/MetadataByOwnerResource:create }
    methods: [POST]
    requirements:
        _format: json
        ownerResourceId: \d+

api_metadata_update_by_owner_resource:
    pattern:  /{ownerResourceId}/metadatas/{metadataKey}
    defaults: { _controller: SimpleITClaireExerciseBundle:ExerciseResource/MetadataByOwnerResource:edit }
    methods: [PUT]
    requirements:
        _format: json
        ownerResourceId: \d+

api_metadata_delete_by_owner_resource:
    pattern:  /{ownerResourceId}/metadatas/{metadataKey}
    defaults: { _controller: SimpleITClaireExerciseBundle:ExerciseResource/MetadataByOwnerResource:delete }
    methods: [DELETE]
    requirements:
        _format: json
        ownerResourceId: \d+

