api_owner_exercise_model_list:
    pattern:  /
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseModel/OwnerExerciseModel:list }
    methods: [GET]
    requirements:
        _format: json

api_owner_exercise_model_view:
    pattern:  /{ownerExerciseModelId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseModel/OwnerExerciseModel:view }
    methods: [GET]
    requirements:
        _format: json
        ownerExerciseModelId: \d+

api_owner_exercise_model_delete:
    pattern:  /{ownerExerciseModelId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseModel/OwnerExerciseModel:delete }
    methods: [DELETE]
    requirements:
        _format: json
        ownerExerciseModelId: \d+

api_exercise_generate_by_owner_exercise_model:
    pattern:  /{ownerExerciseModelId}/exercises/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/CreatedExercise/ExerciseByOwnerExerciseModel:create }
    methods: [POST]
    requirements:
        _format: json
        ownerExerciseModelId: \d+

api_exercise_list_by_owner_exercise_model:
    pattern:  /{ownerExerciseModelId}/exercises/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/CreatedExercise/ExerciseByOwnerExerciseModel:list }
    methods: [GET]
    requirements:
        _format: json
        ownerExerciseModelId: \d+

api_metadata_list_by_owner_exercise_model:
    pattern:  /{ownerExerciseModelId}/metadatas/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseModel/MetadataByOwnerExerciseModel:list }
    methods: [GET]
    requirements:
        _format: json
        ownerExerciseModelId: \d+

api_metadata_edit_all_by_owner_exercise_model:
    pattern:  /{ownerExerciseModelId}/metadatas/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseModel/MetadataByOwnerExerciseModel:editAll }
    methods: [PUT]
    requirements:
        _format: json
        ownerExerciseModelId: \d+

api_metadata_view_by_owner_exercise_model:
    pattern:  /{ownerExerciseModelId}/metadatas/{metadataKey}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseModel/MetadataByOwnerExerciseModel:view }
    methods: [GET]
    requirements:
        _format: json
        ownerExerciseModelId: \d+

api_metadata_create_by_owner_exercise_model:
    pattern:  /{ownerExerciseModelId}/metadatas/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseModel/MetadataByOwnerExerciseModel:create }
    methods: [POST]
    requirements:
        _format: json
        ownerExerciseModelId: \d+

api_metadata_update_by_owner_exercise_model:
    pattern:  /{ownerExerciseModelId}/metadatas/{metadataKey}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseModel/MetadataByOwnerExerciseModel:edit }
    methods: [PUT]
    requirements:
        _format: json
        ownerExerciseModelId: \d+

api_metadata_delete_by_owner_exercise_model:
    pattern:  /{ownerExerciseModelId}/metadatas/{metadataKey}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseModel/MetadataByOwnerExerciseModel:delete }
    methods: [DELETE]
    requirements:
        _format: json
        ownerExerciseModelId: \d+

api_owner_exercise_model_edit:
    pattern:  /{ownerExerciseModelId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseModel/OwnerExerciseModel:edit }
    methods: [PUT]
    requirements:
        _format: json
        ownerExerciseModelId: \d+
