api_owner_resource_list_by_user:
    pattern:  /{ownerId}/owner-resources/
    defaults: { _controller: SimpleITClaireExerciseBundle:ExerciseResource/OwnerResourceByUser:list }
    methods: [GET]
    requirements:
        _format: json
        ownerId: \d+

api_owner_resource_view_by_user:
    pattern:  /{ownerId}/owner-resources/{ownerResourceId}
    defaults: { _controller: SimpleITClaireExerciseBundle:ExerciseResource/OwnerResourceByUser:view }
    methods: [GET]
    requirements:
        _format: json
        ownerResourceId: \d+
        ownerId: \d+

api_owner_exercise_model_list_by_user:
    pattern:  /{ownerId}/owner-exercise-models/
    defaults: { _controller: SimpleITClaireExerciseBundle:ExerciseModel\OwnerExerciseModelByUser:list }
    methods: [GET]
    requirements:
        _format: json
        ownerId: \d+

api_owner_exercise_model_resource_view_by_user:
    pattern:  /{ownerId}/owner-exercise-models/{ownerExerciseModelId}
    defaults: { _controller: SimpleITClaireExerciseBundle:ExerciseModel\OwnerExerciseModelByUser:view }
    methods: [GET]
    requirements:
        _format: json
        ownerExerciseModelId: \d+
        ownerId: \d+

api_owner_knowledge_list_by_user:
    pattern:  /{ownerId}/owner-knowledges/
    defaults: { _controller: SimpleITClaireExerciseBundle:DomainKnowledge/OwnerKnowledgeByUser:list }
    methods: [GET]
    requirements:
        _format: json
        ownerId: \d+

api_owner_knowledge_view_by_user:
    pattern:  /{ownerId}/owner-knowledges/{ownerKnowledgeId}
    defaults: { _controller: SimpleITClaireExerciseBundle:DomainKnowledge/OwnerKnowledgeByUser:view }
    methods: [GET]
    requirements:
        _format: json
        ownerResourceId: \d+
        ownerId: \d+
