simple_it_claire_course:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/course/course.yml"
    prefix:   /courses

simple_it_claire_component_course:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/course/component_course.yml"
    prefix:   components/courses

simple_it_claire_component_course_author:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/user/component_course_author.yml"
    prefix:   components/courses/{courseIdentifier}/authors/

simple_it_claire_component_part_tag:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/associatedContent/component_part_tag.yml"
    prefix:   components/courses/{courseIdentifier}/parts/{partIdentifier}/tags/

simple_it_claire_exercise:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/exercise/exercise.yml"
    prefix:   /exercises

simple_it_claire_exercise_model:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/exercise/exercise_model.yml"
    prefix:   /exercise-models
