claire_course:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/course/routing.yml"
    prefix: /courses

SimpleIT_Claire_Categories:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/Categories/routing.yml"
    prefix: /categories

_internal:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/internal.yml"
    prefix:   /_internal

simple_it_claire_course:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/course/course.yml"
    prefix:   /courses
