simple_it_claire_course:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/course/course.yml"
    prefix:   /courses

simple_it_claire_category:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/associatedContent/category.yml"
    prefix:   /categories

simple_it_claire_component_tag:
    resource: '@SimpleITClaireAppBundle/Resources/config/routing/associatedContent/component_tag.yml'
    prefix : /components/associated-content/tags/

simple_it_claire_associated_content_component_category_by_course:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/associatedContent/component_category_by_course.yml"
    prefix:   components/courses/{courseId}

simple_it_claire_associated_content_component_tag_by_course:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/associatedContent/component_tag_by_course.yml"
    prefix:   components/courses/{courseId}/tags/

simple_it_claire_component_course:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/course/component_course.yml"
    prefix:   components/courses

simple_it_claire_component_course_author:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/user/component_course_author.yml"
    prefix:   components/courses/{courseIdentifier}/authors/

simple_it_claire_component_part_tag:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/associatedContent/component_part_tag.yml"
    prefix:   components/courses/{courseIdentifier}/parts/{partIdentifier}/tags/

simple_it_claire_component_part:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/course/component_part.yml"
    prefix:   /components/courses

simple_it_claire_ui_kit:
    pattern: /claire/uikit
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'SimpleITClaireAppBundle:Uikit:uikit.html.twig'

simple_it_claire_component_exercise_owner_exercise_model:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/exercise/component_owner_exercise_model.yml"
    prefix:   /components/owner-exercise-models

simple_it_claire_component_exercise_exercise_model:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/exercise/component_exercise_model.yml"
    prefix:   /components/exercise-models

simple_it_claire_component_exerciseowner_resources:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/exercise/component_owner_resource.yml"
    prefix:   /components/owner-resources

simple_it_claire_component_exercise_resources:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/exercise/component_resource.yml"
    prefix:   /components/resources

simple_it_claire_component_exercise_attempts:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/exercise/component_attempt.yml"
    prefix:   /components/attempts

simple_it_claire_component_exercise_test_attempts:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/exercise/component_test_attempt.yml"
    prefix:   /components/test-attempts

simple_it_claire_component_exercise_exercises:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/exercise/component_exercise.yml"
    prefix:   /components/exercises

