claire_course:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/course/routing.yml"
    prefix: /courses

SimpleIT_Claire_Categories:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/Categories/routing.yml"
    prefix: /categories

simple_it_claire_course:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/course/course.yml"
    prefix:   /courses

simple_it_claire_component_course:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/course/component_course.yml"
    prefix:   components/courses

simple_it_claire_component_course_author:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/user/component_course_author.yml"
    prefix:   components/courses/{courseIdentifier}/authors/
