simple_it_claire_course:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/course/course.yml"
    prefix:   /courses

simple_it_claire_category:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/associatedContent/category.yml"
    prefix:   /categories

simple_it_claire_associated_content_component_category_by_course:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/associatedContent/component_category_by_course.yml"
    prefix:   components/courses/{courseId}

simple_it_claire_component_course:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/course/component_course.yml"
    prefix:   components/courses

simple_it_claire_component_course_author:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/user/component_course_author.yml"
    prefix:   components/courses/{courseIdentifier}/authors/

simple_it_claire_component_part_tag:
    resource: "@SimpleITClaireAppBundle/Resources/config/routing/associatedContent/component_part_tag.yml"
    prefix:   components/courses/{courseIdentifier}/parts/{partIdentifier}/tags/

simple_it_claire_ui_kit:
    pattern: /claire/uikit
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'SimpleITClaireAppBundle:Uikit:uikit.html.twig'
