course_view:
    pattern:  /{slug}
    defaults: { _controller: SimpleITClaireAppBundle:Course:view }
    requirements:
        _method: get
        slug: \w+

course_list:
    pattern:  /
    defaults: { _controller: SimpleITClaireAppBundle:Course:list }
    requirements:
        _method: get

course_create:
    pattern:  /create
    defaults: { _controller: SimpleITClaireAppBundle:Course:create }
    requirements:
        _method: get|post

course_edit:
    pattern:  /edit/{slug}
    defaults: { _controller: SimpleITClaireAppBundle:Course:edit }
    requirements:
        _method: get|post

