simple_it_claire_associated_content_search_tag_by_course:
    pattern: /searchByCourse
    defaults: {_controller: SimpleITClaireAppBundle:AssociatedContent/Component/TagByCourse:searchListToAdd}
    requirements:
        _method: GET

simple_it_claire_associated_content_edit_tag_by_course:
    pattern: /
    defaults: {_controller: SimpleITClaireAppBundle:AssociatedContent/Component/TagByCourse:editList}
    requirements:
        _method: POST
