simple_it_claire_tag_view:
    pattern: /{categoryIdentifier}/{tagIdentifier}/tutoriels
    defaults: { _controller: TutorialBundle:AssociatedContent/Tag:view }
    requirements:
            _method: GET

