SimpleIT_Claire_categories_list:
    pattern:  /
    defaults: { _controller: SimpleITClaireAppBundle:Category:list }
    requirements:
        _method: get

SimpleIT_Claire_categories_view:
    pattern:  /{slug}
    defaults: { _controller: SimpleITClaireAppBundle:Category:view }
    requirements:
        _method: get

SimpleIT_Claire_categories_tag_view:
    pattern:  /{categorySlug}/tags/{slug}
    defaults: { _controller: SimpleITClaireAppBundle:Category:viewTag }
    requirements:
        _method: get


