
api_exercise_generate_by_owner_exercise_model:
    pattern:  /{ownerExerciseModelId}/exercises/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/CreatedExercise/ExerciseByOwnerExerciseModel:create }
    methods: [POST]
    requirements:
        _format: json
        ownerExerciseModelId: \d+

api_exercise_list_by_owner_exercise_model:
    pattern:  /{ownerExerciseModelId}/exercises/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/CreatedExercise/ExerciseByOwnerExerciseModel:list }
    methods: [GET]
    requirements:
        _format: json
        ownerExerciseModelId: \d+

