api_owner_resource_list_by_user:
    pattern:  /{ownerId}/owner-resources/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/OwnerResourceByUser:list }
    methods: [GET]
    requirements:
        _format: json
        ownerId: \d+

api_owner_resource_view_by_user:
    pattern:  /{ownerId}/owner-resources/{ownerResourceId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/OwnerResourceByUser:view }
    methods: [GET]
    requirements:
        _format: json
        ownerResourceId: \d+
        ownerId: \d+

api_exercise_model_list_by_user:
    pattern:  /{ownerId}/exercise-models/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseModel/ExerciseModelByUser:list }
    methods: [GET]
    requirements:
        _format: json
        ownerId: \d+

api_exercise_model_view_by_user:
    pattern:  /{ownerId}/exercise-models/{exerciseModelId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseModel/ExerciseModelByUser:view }
    methods: [GET]
    requirements:
        _format: json
        exerciseModelId: \d+
        ownerId: \d+

api_owner_knowledge_list_by_user:
    pattern:  /{ownerId}/owner-knowledges/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/OwnerKnowledgeByUser:list }
    methods: [GET]
    requirements:
        _format: json
        ownerId: \d+

api_owner_knowledge_view_by_user:
    pattern:  /{ownerId}/owner-knowledges/{ownerKnowledgeId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/OwnerKnowledgeByUser:view }
    methods: [GET]
    requirements:
        _format: json
        ownerResourceId: \d+
        ownerId: \d+
