attempt_list:
    pattern:  /
    defaults: { _controller: SimpleITExerciseBundle:CreatedExercise/Attempt:list }
    methods: [GET]
    requirements:
        _format: json

attempt_view:
    pattern:  /{attemptId}
    defaults: { _controller: SimpleITExerciseBundle:CreatedExercise/Attempt:view }
    methods: [GET]
    requirements:
        _format: json
        attemptId: \d+

item_list_by_attempt:
    pattern:  /{attemptId}/items/
    defaults: { _controller: SimpleITExerciseBundle:CreatedExercise/ItemByAttempt:list }
    methods: [GET]
    requirements:
        _format: json
        attemptId: \d+

item_view_by_attempt:
    pattern:  /{attemptId}/items/{itemId}
    defaults: { _controller: SimpleITExerciseBundle:CreatedExercise/ItemByAttempt:view }
    methods: [GET]
    requirements:
        _format: json
        attemptId: \d+

answer_list_by_item_by_attempt:
    pattern:  /{attemptId}/items/{itemId}/answers/
    defaults: { _controller: SimpleITExerciseBundle:CreatedExercise/AnswerByItemByAttempt:list }
    methods: [GET]
    requirements:
        _format: json
        attemptId: \d+
        itemId: \d+

answer_create_by_item_by_attempt:
    pattern:  /{attemptId}/items/{itemId}/answers/
    defaults: { _controller: SimpleITExerciseBundle:CreatedExercise/AnswerByItemByAttempt:create }
    methods: [POST]
    requirements:
        _format: json
        attemptId: \d+
        itemId: \d+
