simple_it_claire_component_exercise_exercise_model_create_view:
    pattern: /create
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:createExerciseModelView }
    requirements:
        _method: GET

simple_it_claire_component_exercise_exercise_model_create:
    pattern: /create
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:create }
    requirements:
        _method: POST

simple_it_claire_component_exercise_exercise_model_title_edit_view:
    pattern: /{exerciseModelId}/title
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:editTitleView }
    requirements:
        _method: GET

simple_it_claire_component_exercise_exercise_model_title_edit:
    pattern: /{exerciseModelId}/title
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:titleEdit }
    requirements:
        _method: POST

simple_it_claire_component_exercise_exercise_model_content_edit_view:
    pattern: /{exerciseModelId}/content
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:contentEdit }
    requirements:
        _method: GET

simple_it_claire_component_exercise_exercise_model_content_edit:
    pattern: /{exerciseModelId}/content
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:contentEdit }
    requirements:
        _method: POST

simple_it_claire_component_exercise_exercise_model_required_resource_edit_view:
    pattern: /{exerciseModelId}/required-resources
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/RequiredResourceByExerciseModel:editRequiredResourcesView }
    requirements:
        _method: GET

simple_it_claire_component_exercise_exercise_model_required_resource_edit:
    pattern: /{exerciseModelId}/required-resources
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/RequiredResourceByExerciseModel:RequiredResourceEdit }
    requirements:
        _method: POST

simple_it_claire_component_exercise_exercise_model_list:
    pattern: /
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:list }
    requirements:
        _method: GET

simple_it_claire_component_exercise_exercise_model_view:
    pattern: /{exerciseModelId}
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:view }
    requirements:
        _method: GET
        exerciseModelId: \d+

simple_it_claire_component_exercise_exercise_model_edit:
    pattern: /{exerciseModelId}/edit
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:editView }
    requirements:
        _method: GET
        exerciseModelId: \d+

simple_it_claire_component_exercise_exercise_model_delete:
    pattern: /{exerciseModelId}/delete
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:delete }
    requirements:
        _method: GET
        exerciseModelId: \d+

simple_it_claire_component_exercise_exercise_model_add_to_perso:
    pattern: /{exerciseModelId}/add-to-perso
    defaults: { _controller:SimpleITClaireAppBundle:Exercise/Component/OwnerExerciseModelByExerciseModel:addToPerso }
    requirements:
        _method: GET
        exerciseModelId: \d+


