simple_it_claire_course_component_owner_resource_list:
    pattern: /
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/OwnerResource:list }
    requirements:
        _method: GET

simple_it_claire_course_component_owner_resource_search_list:
    pattern: /search
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/OwnerResource:searchList }
    requirements:
        _method: GET

simple_it_claire_component_exercise_owner_resource_public_edit_view:
    pattern: /{ownerResourceId}/public
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/OwnerResource:editPublicView }
    requirements:
        _method: GET

simple_it_claire_component_exercise_owner_resource_public_edit:
    pattern: /{ownerResourceId}/public
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/OwnerResource:publicEdit }
    requirements:
        _method: POST
