simple_it_claire_component_exercise_exercise_model_type_edit_view:
    pattern: /{exerciseModelId}/type
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:editTypeView }
    requirements:
        _method: GET

simple_it_claire_component_exercise_exercise_model_type_edit:
    pattern: /{exerciseModelId}/type
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:typeEdit }
    requirements:
        _method: POST

simple_it_claire_component_exercise_exercise_model_title_edit_view:
    pattern: /{exerciseModelId}/title
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:editTitleView }
    requirements:
        _method: GET

simple_it_claire_component_exercise_exercise_model_title_edit:
    pattern: /{exerciseModelId}/title
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:titleEdit }
    requirements:
        _method: POST

simple_it_claire_component_exercise_exercise_model_content_edit_view:
    pattern: /{exerciseModelId}/content
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:editContentView }
    requirements:
        _method: GET

simple_it_claire_component_exercise_exercise_model_multiple_choice_content_edit:
    pattern: /{exerciseModelId}/multiple-choice/content
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:multipleChoiceContentEdit }
    requirements:
        _method: POST

simple_it_claire_component_exercise_exercise_model_group_items_content_edit:
    pattern: /{exerciseModelId}/group-items/content
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:groupItemsContentEdit }
    requirements:
        _method: POST

simple_it_claire_component_exercise_exercise_model_order_items_content_edit:
    pattern: /{exerciseModelId}/order-items/content
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:orderItemsContentEdit }
    requirements:
        _method: POST

simple_it_claire_component_exercise_exercise_model_pair_items_content_edit:
    pattern: /{exerciseModelId}/pair-items/content
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:pairItemsContentEdit }
    requirements:
        _method: POST

simple_it_claire_component_exercise_exercise_model_required_resource_edit_view:
    pattern: /{exerciseModelId}/required-resources
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/RequiredResourceByExerciseModel:editRequiredResourcesView }
    requirements:
        _method: GET

simple_it_claire_component_exercise_exercise_model_required_resource_edit:
    pattern: /{exerciseModelId}/required-resources
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/RequiredResourceByExerciseModel:RequiredResourceEdit }
    requirements:
        _method: POST

