simple_it_claire_course_component_owner_resource_browser:
    pattern: /browser
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/OwnerResource:browserView }
    requirements:
        _method: GET

simple_it_claire_course_component_owner_resource_list:
    pattern: /
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/OwnerResource:list }
    requirements:
        _method: GET

simple_it_claire_course_component_owner_resource_search_list:
    pattern: /search
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/OwnerResource:searchList }
    requirements:
        _method: GET

simple_it_claire_component_exercise_owner_resource_public_edit_view:
    pattern: /{ownerResourceId}/public
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/OwnerResource:editPublicView }
    requirements:
        _method: GET

simple_it_claire_component_exercise_owner_resource_public_edit:
    pattern: /{ownerResourceId}/public
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/OwnerResource:publicEdit }
    requirements:
        _method: POST

simple_it_claire_component_exercise_owner_resource_metadata_edit_view:
    pattern: /{ownerResourceId}/metadatas
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/MetadataByOwnerResource:editMetadataView }
    requirements:
        _method: GET

simple_it_claire_component_exercise_owner_resource_metadata_edit:
    pattern: /{ownerResourceId}/metadatas
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/MetadataByOwnerResource:MetadataEdit }
    requirements:
        _method: POST

simple_it_claire_component_exercise_multiple_owner_resource_metadata_edit_view:
    pattern: /multiple-metadatas-create
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/OwnerResource:createMultipleMetadataView }
    requirements:
        _method: GET

simple_it_claire_component_exercise_multiple_owner_resource_metadata_edit:
    pattern: /multiple-metadatas-create
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/OwnerResource:multipleMetadataCreate }
    requirements:
        _method: POST

simple_it_claire_component_exercise_multiple_owner_resource_key_metadata_edit_view:
    pattern: /multiple-key-create
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/OwnerResource:createMultipleKeyMetadataView }
    requirements:
        _method: GET

simple_it_claire_component_exercise_multiple_owner_resource_key_metadata_edit:
    pattern: /multiple-key-create
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/OwnerResource:multipleKeyMetadataCreate }
    requirements:
        _method: POST

