simple_it_exercise_model_view:
    pattern: /{exerciseModelId}
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:view }
    requirements:
        _method: GET
        exerciseModelId: \d+

simple_it_exercise_generate:
    pattern: /{exerciseModelId}/new
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseByExerciseModel:generate }
    requirements:
        _method: GET
        exerciseModelId: \d+

simple_it_claire_exercise_exercise_model_edit:
    pattern: /{exerciseModelId}/edit
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:editView }
    requirements:
        _method: GET
        exerciseModelId: \d+

simple_it_claire_exercise_exercise_model_create_view:
    pattern: /create
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:createExerciseModelView }
    requirements:
        _method: GET

simple_it_claire_exercise_exercise_model_create:
    pattern: /create
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:create }
    requirements:
        _method: POST

simple_it_claire_exercise_exercise_model_delete:
    pattern: /{exerciseModelId}/delete
    defaults: { _controller: SimpleITClaireAppBundle:Exercise/Component/ExerciseModel:delete }
    requirements:
        _method: GET
        exerciseModelId: \d+
