exercise_model_list:
    pattern:  /
    defaults: { _controller: SimpleITExerciseBundle:ExerciseModel\ExerciseModel:list }
    methods: [GET]
    requirements:
        _format: json

exercise_model_view:
    pattern:  /{exerciseModelId}
    defaults: { _controller: SimpleITExerciseBundle:ExerciseModel\ExerciseModel:view }
    methods: [GET]
    requirements:
        _format: json
        exerciseModelId: \d+

exercise_model_create:
    pattern:  /
    defaults: { _controller: SimpleITExerciseBundle:ExerciseModel\ExerciseModel:create }
    methods: [POST]
    requirements:
        _format: json

exercise_model_edit:
    pattern:  /{exerciseModelId}
    defaults: { _controller: SimpleITExerciseBundle:ExerciseModel\ExerciseModel:edit }
    methods: [PUT]
    requirements:
        _format: json
        exercise_modelId: \d+

exercise_model_delete:
    pattern:  /{exerciseModelId}
    defaults: { _controller: SimpleITExerciseBundle:ExerciseModel\ExerciseModel:delete }
    methods: [DELETE]
    requirements:
        _format: json
        exerciseModelId: \d+

owner_exercise_model_create_by_exercise_model:
    pattern:  /{exerciseModelId}/owner-exercise-models/
    defaults: { _controller: SimpleITExerciseBundle:ExerciseModel\OwnerExerciseModelByExerciseModel:create }
    methods: [POST]
    requirements:
        _format: json
        exerciseModelId: \d+

owner_exercise_model_edit_by_exercise_model:
    pattern:  /{exerciseModelId}/owner-exercise-models/{ownerExerciseModelId}
    defaults: { _controller: SimpleITExerciseBundle:ExerciseModel\OwnerExerciseModelByExerciseModel:edit }
    methods: [PUT]
    requirements:
        _format: json
        exerciseModelId: \d+
        ownerExerciseModelId: \d+

owner_exercise_model_list_by_exercise_model:
    pattern:  /{exerciseModelId}/owner-exercise-models/
    defaults: { _controller: SimpleITExerciseBundle:ExerciseModel\OwnerExerciseModelByExerciseModel:list }
    methods: [GET]
    requirements:
        _format: json
        exerciseModelId: \d+

owner_exercise_model_view_by_exercise_model:
    pattern:  /{exerciseModelId}/owner-exercise-models/{ownerExerciseModelId}
    defaults: { _controller: SimpleITExerciseBundle:ExerciseModel\OwnerExerciseModelByExerciseModel:view }
    methods: [GET]
    requirements:
        _format: json
        ownerExerciseModelId: \d+
        exerciseModelId: \d+

exercise_model_add_requirement:
    pattern:  /{exerciseModelId}/required-resources/{reqResId}
    defaults: { _controller: SimpleITExerciseBundle:ExerciseModel\RequiredResourceByExerciseModel:add }
    methods: [POST]
    requirements:
        _format: json
        exerciseModelId: \d+
        reqResId: \d+

exercise_model_delete_requirement:
    pattern:  /{exerciseModelId}/required-resources/{reqResId}
    defaults: { _controller: SimpleITExerciseBundle:ExerciseModel\RequiredResourceByExerciseModel:delete }
    methods: [DELETE]
    requirements:
        _format: json
        exerciseModelId: \d+
        reqResId: \d+

exercise_model_update_required_resource:
    pattern:  /{exerciseModelId}/required-resources/
    defaults: { _controller: SimpleITExerciseBundle:ExerciseModel\RequiredResourceByExerciseModel:edit }
    methods: [PUT]
    requirements:
        _format: json
        exerciseModelId: \d+
        reqResId: \d+
