item_list:
    pattern:  /
    defaults: { _controller: SimpleITExerciseBundle:CreatedExercise/Item:list }
    methods: [GET]
    requirements:
        _format: json

item_view:
    pattern:  /{itemId}
    defaults: { _controller: SimpleITExerciseBundle:CreatedExercise/Item:view }
    methods: [GET]
    requirements:
        _format: json
        itemId: \d+

item_add_answer:
    pattern:  /{itemId}/answers/
    defaults: { _controller: SimpleITExerciseBundle:CreatedExercise/AnswerByItem:create }
    methods: [POST]
    requirements:
        _format: json
        itemId: \d+

answer_list_by_item:
    pattern:  /{itemId}/answers/
    defaults: { _controller: SimpleITExerciseBundle:CreatedExercise/AnswerByItem:list }
    methods: [GET]
    requirements:
        _format: json
        itemId: \d+

answer_by_item_view:
    pattern:  /{itemId}/answers/{answerId}
    defaults: { _controller: SimpleITExerciseBundle:CreatedExercise/AnswerByItem:view }
    methods: [GET]
    requirements:
        _format: json
        itemId: \d+
        answerId: \d+
