test_list:
    pattern:  /
    defaults: { _controller: SimpleITExerciseBundle:Test/Test:list }
    methods: [GET]
    requirements:
        _format: json

test_view:
    pattern:  /{testId}
    defaults: { _controller: SimpleITExerciseBundle:Test/Test:view }
    methods: [GET]
    requirements:
        _format: json
        testId: \d+

test_attempt_list_by_test:
    pattern:  /{testId}/test-attempts/
    defaults: { _controller: SimpleITExerciseBundle:Test/TestAttemptByTest:list }
    methods: [GET]
    requirements:
        _format: json
        testId: \d+

test_attempt_create:
    pattern:  /{testId}/test-attempts/
    defaults: { _controller: SimpleITExerciseBundle:Test/TestAttemptByTest:create }
    methods: [POST]
    requirements:
        _format: json
        testId: \d+
